name: bloodapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  location: ^4.4.0
  logger: null
  syncfusion_flutter_charts: ^20.3.48
  syncfusion_flutter_maps: ^20.3.48

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0071A4"
  image: images/Group.png
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    # Add assets from the images directory to the application.
    - images/
    - assets/images/
