// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDtb1QxcVPOyB7E5g_Rxm2E1l566hhJI',
    appId: '1:1048710249305:web:d777df8108b64d64236a48',
    messagingSenderId: '1048710249305',
    projectId: 'q-blood-bank',
    authDomain: 'q-blood-bank.firebaseapp.com',
    storageBucket: 'q-blood-bank.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_uKneBHFR0oYvpBghpiJuIODBWBsldA',
    appId: '1:1048710249305:android:bfd07c0718270ce4236a48',
    messagingSenderId: '1048710249305',
    projectId: 'q-blood-bank',
    storageBucket: 'q-blood-bank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_Qq17DJnT1IA_o1kzN9jiNKjgzSR4Po',
    appId: '1:1048710249305:ios:2e6a7fc6929bfe3f236a48',
    messagingSenderId: '1048710249305',
    projectId: 'q-blood-bank',
    storageBucket: 'q-blood-bank.appspot.com',
    iosClientId: '1048710249305-98b454v1rk633l87vm09nor5sdo2qn7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_Qq17DJnT1IA_o1kzN9jiNKjgzSR4Po',
    appId: '1:1048710249305:ios:2e6a7fc6929bfe3f236a48',
    messagingSenderId: '1048710249305',
    projectId: 'q-blood-bank',
    storageBucket: 'q-blood-bank.appspot.com',
    iosClientId: '1048710249305-98b454v1rk633l87vm09nor5sdo2qn7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFlutterFirebase',
  );
}
